spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
msg: vertechz international
#server:
#  port: 8081
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
