server:
  port: 8081  # Change as needed

spring:
  application:
    name: my-microservice  # Unique name for service discovery (e.g., Eureka)

  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'none', 'validate', 'update', or 'create-drop' as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Optional Eureka config if you're using service discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


